<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contact_fa-solid fa-magnifying-glass search (3)</name>
   <tag></tag>
   <elementGuidId>cbfebf46-8a1a-49ff-8eb6-1a7527bb50c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-magnifying-glass.search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navbar']/div/div/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a0e02263-1e5a-462f-a490-8254e4e5a1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-magnifying-glass search</value>
      <webElementGuid>3bc49166-09fd-4f19-bd86-0fb50cfeb449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;searchBox&quot;]/div[@class=&quot;searchToggle&quot;]/i[@class=&quot;fa-solid fa-magnifying-glass search&quot;]</value>
      <webElementGuid>cb04cc8f-0b12-4c34-8b3b-3743ef167684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navbar']/div/div/i[2]</value>
      <webElementGuid>f3e23c91-0411-4166-a881-c84bddcccdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>ed889310-e122-4e8b-add3-2ca7faef93cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
