<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact_txt (119)</name>
   <tag></tag>
   <elementGuidId>a00a0a52-b183-4159-8d57-13ed984ebcac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txt&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66b38fb2-4671-4304-91e6-be39360dfe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2953d196-745b-42e1-8026-3864661736fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>97fa8494-5ee6-4734-a64c-d3f733fb4cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name</value>
      <webElementGuid>05b154ca-95be-4ea2-9eb1-b53fbeccc0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginPopup&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;login&quot;]/form[1]/input[1]</value>
      <webElementGuid>10f98a90-5b4e-4428-8234-66a2143aa422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txt']</value>
      <webElementGuid>36703d6d-4d22-49fb-a62f-95d4c1b1358c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginPopup']/div/div/form/input</value>
      <webElementGuid>b321183e-19f2-4f9b-9731-9700f695ed7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>fdefa6d0-59e0-4f19-86b9-d056a69c53a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt' and @placeholder = 'User name']</value>
      <webElementGuid>6edd6cf0-43ce-4626-bfce-adcb20cdbeee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
